#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# Local modules
mod 'softservesag/profiles', :path => 'local_modules/profiles'
mod 'softservesag/roles', :path => 'local_modules/roles'
mod 'softservesag/jdk_oracle', :path => 'local_modules/jdk_oracle'
mod 'softservesag/log_generator', :path => 'local_modules/log_generator'
mod 'softservesag/cloudera_director_client', :path => 'local_modules/cloudera_director_client'
